<?php namespace JF;
/**

Copyright 2019 JQueryForm.com
License: http://www.jqueryform.com/license.php

FormID:  jqueryform-2fc625
Date:    2019-11-08 06:25:55
Version: v3.0.3
Generated by http://www.jqueryform.com

PHP 5.3+ is required.
If mailgun is used AND the form has file upload field, PHP 5.5+ is required.

*/

class Config {
	private static $config;

    public static function getConfig( $decode = true ){
    	self::$config = self::_getConfig( $decode );
    	self::overwriteConfig();
    	return self::$config;
    }

    private static function _getConfig( $decode = true ){
        ob_start();
        // ---------------------------------------------------------------------
        // JSON format config
        // Note: please make a copy before you edit config manually
        // ---------------------------------------------------------------------

/**JSON_START**/ ?>
{
    "formId": "jqueryform-2fc625",
    "email": {
        "to": "maximsenko@gmail.com",
        "cc": "",
        "bcc": "",
        "subject": "",
        "template": ""
    },
    "admin": {
        "users": "admin:1a57c",
        "dataDelivery": "emailAndFile"
    },
    "thankyou": {
        "url": "",
        "message": "",
        "seconds": "10"
    },
    "autoResponse": {
        "includeAttachments": true,
        "subject": "",
        "template": ""
    },
    "seo": {
        "trackerId": "",
        "title": "",
        "description": "",
        "keywords": "",
        "author": ""
    },
    "mailer": "local",
    "smtp": {
        "host": "",
        "user": "",
        "password": ""
    },
    "mailgun": {
        "domain": "",
        "apiKey": "",
        "fromEmail": "",
        "fromName": ""
    },
    "styles": {
        "iCheck": {
            "enabled": true,
            "skin": "flat",
            "colorScheme": "black"
        },
        "Select2": {
            "enabled": false
        }
    },
    "logics": [],
    "fields": [
        {
            "label": "\u0417\u0430\u043f\u043e\u043b\u043d\u0438\u0442\u0435 \u0412\u0430\u0448\u0438 \u0438\u043c\u044f \u0438 \u0438 \u0444\u0430\u043c\u0438\u043b\u0438\u044e ",
            "field_type": "name",
            "field_options": {
                "size": "small",
                "sender": "",
                "images": {
                    "urls": "",
                    "slideshow": false
                },
                "validators": {
                    "required": {
                        "enabled": true
                    },
                    "minlength": {
                        "enabled": false
                    },
                    "maxlength": {
                        "enabled": false
                    },
                    "equalto": {
                        "enabled": false
                    }
                },
                "placeholder": "\u0413\u043e\u0441\u0442\u044c 1",
                "addon": {
                    "leftIcon": "glyphicon glyphicon-user"
                }
            },
            "id": "f1",
            "cid": "c1"
        },
        {
            "label": "",
            "field_type": "name",
            "field_options": {
                "size": "small",
                "sender": "",
                "images": {
                    "urls": "",
                    "slideshow": false
                },
                "validators": {
                    "required": {
                        "enabled": false
                    },
                    "minlength": {
                        "enabled": false
                    },
                    "maxlength": {
                        "enabled": true,
                        "val": ""
                    },
                    "equalto": {
                        "enabled": false
                    }
                },
                "placeholder": "\u0413\u043e\u0441\u0442\u044c 2",
                "addon": {
                    "leftIcon": "glyphicon glyphicon-user"
                }
            },
            "cid": "c55",
            "id": "f14"
        },
        {
            "label": " ",
            "field_type": "name",
            "field_options": {
                "size": "small",
                "sender": "",
                "images": {
                    "urls": "",
                    "slideshow": false
                },
                "validators": {
                    "required": {
                        "enabled": false
                    },
                    "minlength": {
                        "enabled": false
                    },
                    "maxlength": {
                        "enabled": false
                    },
                    "equalto": {
                        "enabled": false
                    }
                },
                "placeholder": "\u0413\u043e\u0441\u0442\u044c 3",
                "addon": {
                    "leftIcon": "glyphicon glyphicon-user"
                }
            },
            "cid": "c64",
            "id": "f15"
        },
        {
            "label": "\u041f\u043e\u0434\u0442\u0432\u0435\u0440\u0434\u0438\u0442\u044c \u043f\u0440\u0438\u0441\u0443\u0442\u0441\u0442\u0432\u0438\u0435",
            "field_type": "checkboxes",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "\u041f\u0440\u0438\u0441\u0443\u0442\u0441\u0442\u0432\u0438\u0435 \u043f\u043e\u0434\u0442\u0432\u0435\u0440\u0436\u0434\u0430\u044e",
                        "checked": false
                    },
                    {
                        "label": "\u041a \u0441\u043e\u0436\u0430\u043b\u0435\u043d\u0438\u044e, \u043d\u0435 \u0441\u043c\u043e\u0433\u0443 \u0431\u044b\u0442\u044c",
                        "checked": false,
                        "value": ""
                    }
                ],
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)",
                        "enabled": false,
                        "val": ""
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)",
                        "enabled": false,
                        "val": "#empty"
                    },
                    "required": {
                        "enabled": true,
                        "msg": "\u0412\u044b \u043d\u0435 \u0437\u0430\u043f\u043e\u043b\u043d\u0438\u043b\u0438 \u043e\u0434\u043d\u043e \u0438\u0437 \u043f\u043e\u043b\u0435\u0439!"
                    }
                },
                "presetJson": "",
                "hidden": false
            },
            "id": "f9",
            "cid": "c64",
            "labelHide": false
        },
        {
            "label": "\u041d\u0443\u0436\u0435\u043d \u043b\u0438 \u0412\u0430\u043c \u0442\u0440\u0430\u043d\u0441\u0444\u0435\u0440 \u0434\u043e \u0443\u0441\u0430\u0434\u044c\u0431\u044b? (\u0411\u0430\u0440\u0430\u043d\u043e\u0432\u0438\u0447\u0438 - \u0414\u043e\u0431\u0440\u0438\u0446\u0438\u043d\u043e)",
            "field_type": "checkboxes",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "\u0414\u0430",
                        "checked": false
                    },
                    {
                        "label": "\u041d\u0435\u0442, \u044f \u043d\u0430 \u043c\u0430\u0448\u0438\u043d\u0435",
                        "checked": false,
                        "value": ""
                    }
                ],
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)",
                        "enabled": false,
                        "val": ""
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)",
                        "enabled": false,
                        "val": "#empty"
                    },
                    "required": {
                        "enabled": false,
                        "msg": "\u0412\u044b \u043d\u0435 \u0437\u0430\u043f\u043e\u043b\u043d\u0438\u043b\u0438 \u043e\u0434\u043d\u043e \u0438\u0437 \u043f\u043e\u043b\u0435\u0439!"
                    }
                },
                "presetJson": "",
                "hidden": false
            },
            "cid": "c39",
            "labelHide": false,
            "id": "f12"
        },
        {
            "label": "\u0412\u0438\u043d\u043d\u0430\u044f \u043a\u0430\u0440\u0442\u0430 (\u0412\u0430\u0448\u0435 \u043f\u0440\u0435\u0434\u043f\u043e\u0447\u0442\u0435\u043d\u0438\u0435)",
            "field_type": "checkboxes",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "\u0428\u0430\u043c\u043f\u0430\u043d\u0441\u043a\u043e\u0435",
                        "checked": false
                    },
                    {
                        "label": "\u0412\u0438\u043d\u043e \u0431\u0435\u043b\u043e\u0435 (\u0441\u0443\u0445\u043e\u0435)",
                        "checked": false,
                        "value": ""
                    },
                    {
                        "label": "\u0412\u0438\u043d\u043e \u0431\u0435\u043b\u043e\u0435 (\u043f\u043e\u043b\u0443\u0441\u0443\u0445\u043e\u0435)",
                        "checked": null
                    },
                    {
                        "label": "\u0412\u0438\u043d\u043e \u0431\u0435\u043b\u043e\u0435 (\u043f\u043e\u043b\u0443\u0441\u043b\u0430\u0434\u043a\u043e\u0435)",
                        "checked": null
                    },
                    {
                        "label": "\u0412\u0438\u043d\u043e \u043a\u0440\u0430\u0441\u043d\u043e\u0435 (\u0441\u0443\u0445\u043e\u0435)",
                        "checked": null
                    },
                    {
                        "label": "\u0412\u0438\u043d\u043e \u043a\u0440\u0430\u0441\u043d\u043e\u0435 (\u043f\u043e\u043b\u0443\u0441\u0443\u0445\u043e\u0435)",
                        "checked": null
                    },
                    {
                        "label": "\u0412\u0438\u043d\u043e \u043a\u0440\u0430\u0441\u043d\u043e\u0435 (\u043f\u043e\u043b\u0443\u0441\u043b\u0430\u0434\u043a\u043e\u0435)",
                        "checked": null
                    }
                ],
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)",
                        "enabled": false,
                        "val": ""
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)",
                        "enabled": false,
                        "val": "#empty"
                    },
                    "required": {
                        "enabled": false,
                        "msg": "\u0412\u044b \u043d\u0435 \u0437\u0430\u043f\u043e\u043b\u043d\u0438\u043b\u0438 \u043e\u0434\u043d\u043e \u0438\u0437 \u043f\u043e\u043b\u0435\u0439!"
                    }
                },
                "presetJson": "",
                "hidden": false
            },
            "cid": "c32",
            "labelHide": false,
            "id": "f11"
        },
        {
            "label": "Submit Button",
            "field_type": "submit",
            "required": true,
            "field_options": {
                "page": {
                    "title": "Submit",
                    "labelPrev": "< Back",
                    "showPageNumnber": false,
                    "pageNumberText": "{page} \/ {total}"
                },
                "images": {
                    "urls": "",
                    "slideshow": false
                }
            },
            "labelHide": true,
            "submit": {
                "label": "\u041e\u0442\u043f\u0440\u0430\u0432\u0438\u0442\u044c",
                "icon": "",
                "checkRequiredFields": ""
            },
            "id": "f0",
            "cid": "c0"
        }
    ],
    "gdpr": {
        "consentFieldId": "",
        "saveData": "always"
    },
    "licenseKey": ""
}
<?php /**JSON_END**/

        $json = ob_get_clean() ;

        return $decode ? json_decode( trim($json), true ) : $json;
    } // end of getConfig()

    private static function getValue( $fieldId, $default = NULL ){
        return isset( $_POST[$fieldId] ) ? $_POST[$fieldId] : $default ;
    }

    private static function overwriteConfig(){
    	//self::get_to();
    }

    private static function get_to(){
    	$value = self::getValue( 'c25' );
    	$to = array(
    		'Option 1' => 'a@a.com',
    		'Option 2' => 'b@b.com',
    		'Option 3' => 'c@c.com',
    	);

    	if( isset( $to[$value] ) ){
    		self::$config['email']['to'] = $to[ $value ];
    	};
    }

} // end of Config class